@token = eyJhbGciOiJIUzI1NiIsImtpZCI6IjhyZmFLTklRdHhNS2RFcnAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ZocWRxYWVxcXVjb2JkbHp4aHRwLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI1NWY5NWU2ZS1mMWUxLTQ1ZDEtOTkzMi1lOTExMzhmZTA2YmIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzYwMTE4MDg0LCJpYXQiOjE3NjAxMTQ0ODQsImVtYWlsIjoiYWhtZXRAZXhhbXBsZS5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJzdE5hbWUiOiJBaG1ldCIsImxhc3ROYW1lIjoiWcSxbG1heiIsInBob25lTnVtYmVyIjoiNTU1MTIzNDU2NyJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzYwMTE0NDg0fV0sInNlc3Npb25faWQiOiIzNjRjNjdiMC1jNGE3LTRjZWYtYmEwYS1jMWYzMDhjZWI5OTUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.lqOl301YnPEwLPCAn_J4nXWWwM51uhF5-_dUdQav6lM

### 1. Register
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "firstName": "Ahmet",
  "lastName": "Yılmaz",
  "email": "ahmet@example.com",
  "phoneNumber": "5551234567",
  "password": "SecurePass123!"
}

### 2. Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "ahmet@example.com",
  "password": "SecurePass123!"
}

### 3. Get My Profile (JWT'den)
GET http://localhost:8080/api/users/me
Authorization: Bearer {{token}}

### 4. Create Property
POST http://localhost:8080/api/properties
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Villa Antalya",
  "description": "Güzel villa",
  "totalVillas": 3,
  "villaType": "Luxury",
  "locationName": "Belek",
  "nightlyRate": 500.00
}